### PR TITLE
closes #69 - allow missing template path

### LINKED ISSUE #69: remove templatePath option - parent application should define this
Default express view rendering should be used. Instead of the current pattern of `router.use(wizard)`, each journey should have its own `express()` instance rather than `router`, each with their own views directory set on the app instance. This way default view rendering behaviour can be taken advantage of and we wont need to override with templatePath.

### PR DESCRIPTION
**Pull request by joefitter**
This allows the default views directory to be used by express internally

* removed default template path
* check if templatePath if defined before prepending

### CODE REVIEW

**Comment by joefitter** [comment]
@gavboulton @easternbloc @JoeChapman @HughePaul would you mind having a look at this? It would be a major bump as any app currently using wizard without a templatePath will have it implicitly set to 'pages'

**Comment by gavboulton** [comment]
Can you add a test please.

This will be a breaking change.

**Comment by joefitter** [comment]
@gavboulton test added

**Comment by gavboulton** [comment]
LGTM :+1:

**Comment by easternbloc** [comment]
LGTM

**Comment by easternbloc** [comment]
@gavboulton can you merge that now pwease and gis a version bump

**Comment by gavboulton** [comment]
hmpo-form-wizard@5.0.0 published.

**Pull request merged**
