### PR TITLE
Updated example app and readme to demonstrate forking

### PR DESCRIPTION
**Pull request by joefitter**
* bumped hmpo-form-controller to ^0.7
* updated example app to include a fork
* updated readme with link to forking docs

### CODE REVIEW

**Comment by joefitter** [comment]
@gavboulton @easternbloc @JoeChapman @daniel-ac-martin PR to update example form to demonstrate forking functionality

**Comment by JoeChapman** [comment]
LGTM

**Comment by easternbloc** [comment]
looking...

**Comment by easternbloc** [comment]
👍

**Comment by gavboulton** [comment]
I was going to say that left and right both seem like forks and was going to suggest straight and fork. You would have said I was being too pedantic and to shut up. So, good job!

**Comment by joefitter** [comment]
I know what you mean @gavboulton - I think once we revisit forks we will probably expand `next` to take an object or function so any result would have equal weight

**Pull request merged**
