### PR TITLE
fix endless loop in invalidation checking

### PR DESCRIPTION
**Pull request by joefitter**
* check forks haven't been added to list of steps before traversing
* only perform on POST

### CODE REVIEW

**Comment by gavboulton** [comment]
Can you add some tests please.

**Comment by joefitter** [comment]
@gavboulton - have done - this is just a PR to so-master - I'll patch that back to master in a separate PR once merged

**Comment by easternbloc** [comment]
lgtm

**Comment by joefitter** [comment]
🙌

**Comment by gavboulton** [comment]
:+1:

**Pull request merged**
