### PR TITLE
feature - expose step route to controller

### PR DESCRIPTION
**Pull request by joefitter**
Currently a conroller doen't get passed the key of its step, added options.route on controller init with the step key

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @gxxm tiny one - should have been done a while ago!

**Comment by easternbloc** [comment]
@gavboulton fancy merging this? It's just a tiny one but somehow doesn't exist at the moment

**Comment by joefitter** [comment]
this is to so-master.

**Comment by easternbloc** [comment]
@joefitter so it is @gavboulton ignore me

**Pull request merged**
