### PR TITLE
Allow specifying a next function by name as a controller method

### PR DESCRIPTION
**Pull request by HughePaul**
- Allow specifying a next function by name as a controller method

### CODE REVIEW

**Comment by oliverweighell** [comment]
What's the use case? Would also be good to get more explanation on the new flexibility with 'next' in the readme.

**Comment by HughePaul** [comment]
```javascript
class Controller extends BaseController {
  branchingFunction(req, res, con) {
    return true;
  }
}
```
A branching function which is a class method can already be specified using the prototype:
```javascript
'/step': {
  next: [
    { fn: Controller.prototype.branchingFunction, next: 'gohere' },
    'gothere'
  ]
}
```
This change allows a controller class method to be specified by name. It's just a nice-to-have.
```javascript
'/step': {
  next: [
    { fn: 'branchingFunction', next: 'gohere' },
    'gothere'
  ]
}

```

**Comment by gavboulton** [comment]
LGTM.

**Comment by oliverweighell** [comment]
We should update the advice in the readme - https://github.com/UKHomeOffice/passports-form-wizard/blob/master/README.md#next-steps. Aside from that, LGTM.

**Comment by HughePaul** [comment]
Added to the readme

**Pull request merged**
