### PR TITLE
Pass `req.form.values` to translate function - this is needed for con…

### PR DESCRIPTION
**Pull request by joefitter**
…ditional translation lookup

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @gxxm please!

**Comment by gxxm** [comment]
:thumbsup: :thumbsup:

**Comment by JoeChapman** [comment]
If the tests pass, I'll merge it

**Comment by joefitter** [comment]
oops - dint mean to close that

**Comment by joefitter** [comment]
yes I did

**Pull request closed without merging**
